
INSERT INTO AUTOR(ID_AUTOR, NM_AUTOR, CPF_AUTOR) VALUES( 1, ' ANDRE ', '4534534534');
INSERT INTO AUTOR(ID_AUTOR, NM_AUTOR, CPF_AUTOR) VALUES( 2, ' REINALDO ', '4453453');

INSERT INTO LIVRO(ID_AUTOR, NM_LIVRO, NM_PAGINA) VALUES( 1, ' Teste Livro 1 ', 220);
INSERT INTO LIVRO(ID_AUTOR, NM_LIVRO, NM_PAGINA) VALUES( 1, ' Teste ', 220);
INSERT INTO LIVRO(ID_AUTOR, NM_LIVRO, NM_PAGINA) VALUES( 1, ' Livro 1 ', 220);
INSERT INTO LIVRO(ID_AUTOR, NM_LIVRO, NM_PAGINA) VALUES( 2, ' Livro Joao ', 220);
INSERT INTO LIVRO(ID_AUTOR, NM_LIVRO, NM_PAGINA) VALUES( 2, ' Livro joao ', 220);
INSERT INTO LIVRO(ID_AUTOR, NM_LIVRO, NM_PAGINA) VALUES( 2, ' Livro JONATAS ', 220);
INSERT INTO LIVRO(ID_AUTOR, NM_LIVRO, NM_PAGINA) VALUES( 2, ' Livro Maria ', 220);
INSERT INTO LIVRO(ID_AUTOR, NM_LIVRO, NM_PAGINA) VALUES( 1, ' Livro Marta ', 220);
INSERT INTO LIVRO(ID_AUTOR, NM_LIVRO, NM_PAGINA) VALUES( 1, ' Livro 5 ', 220);
INSERT INTO LIVRO(ID_AUTOR, NM_LIVRO, NM_PAGINA) VALUES( 2, ' Livro 4 ', 220);
